module Ordliste.Tui.WordData

open System
open System.IO

/// The three word classes generated by Generate.fsx.
type Category =
    | Substantiv
    | Adjektiv
    | Verb

    member this.FileName =
        match this with
        | Substantiv -> "substantiv.txt"
        | Adjektiv -> "adjektiv.txt"
        | Verb -> "verb.txt"

    member this.DisplayName =
        match this with
        | Substantiv -> "Substantiv"
        | Adjektiv -> "Adjektiv"
        | Verb -> "Verb"

let allCategories = [ Substantiv; Adjektiv; Verb ]

/// Walk up from a starting directory looking for an "ordliste" folder that
/// contains the generated word lists. Returns the folder path if found.
let private walkUpFor (start: string) =
    let rec loop (dir: DirectoryInfo) =
        if isNull dir then
            None
        else
            let candidate = Path.Combine(dir.FullName, "ordliste")
            if Directory.Exists candidate
               && File.Exists(Path.Combine(candidate, Substantiv.FileName)) then
                Some candidate
            else
                loop dir.Parent

    loop (DirectoryInfo start)

/// The directory holding the word lists, resolved once on first use.
/// We search from both the current working directory and the location of the
/// executable so the app works whether run via `dotnet run` or a published build.
let ordlisteDir =
    lazy
        ([ Directory.GetCurrentDirectory(); AppContext.BaseDirectory ]
         |> List.tryPick walkUpFor
         |> function
             | Some dir -> dir
             | None ->
                 failwith
                     "Fant ikke 'ordliste'-mappa med ordlistene. Kjør appen fra prosjektet, eller generer listene med Generate.fsx først.")

/// Load a single word list from disk.
let load (category: Category) =
    Path.Combine(ordlisteDir.Value, category.FileName) |> File.ReadAllLines

/// Load every word list into a map keyed by category.
let loadAll () =
    allCategories
    |> List.map (fun c -> c, load c)
    |> Map.ofList
